from __future__ import annotations

STARTER_PLAYERS = [
    {
        "player_id": "fl-mike-maignan",
        "name": "Mike Maignan",
        "nation": "🇫🇷",
        "club": "AC Milan",
        "position": "GK",
        "secondary_positions": [],
        "rarity": "ELITE",
        "ovr": 87,
        "pace": 52,
        "shooting": 34,
        "passing": 78,
        "dribbling": 45,
        "defending": 88,
        "physical": 84,
        "preferred_foot": "Right",
        "traits": ["Sweeper Keeper", "Reflexes"],
    },
    {
        "player_id": "fl-ruben-dias",
        "name": "Rúben Dias",
        "nation": "🇵🇹",
        "club": "Manchester City",
        "position": "DEF",
        "secondary_positions": ["CB"],
        "rarity": "ELITE",
        "ovr": 89,
        "pace": 68,
        "shooting": 35,
        "passing": 81,
        "dribbling": 48,
        "defending": 92,
        "physical": 88,
        "preferred_foot": "Right",
        "traits": ["Leader", "Interceptor"],
    },
    {
        "player_id": "fl-william-saliba",
        "name": "William Saliba",
        "nation": "🇫🇷",
        "club": "Arsenal",
        "position": "DEF",
        "secondary_positions": ["CB"],
        "rarity": "RARE",
        "ovr": 87,
        "pace": 82,
        "shooting": 30,
        "passing": 78,
        "dribbling": 52,
        "defending": 90,
        "physical": 86,
        "preferred_foot": "Right",
        "traits": ["Recovery Pace", "Strong"],
    },
    {
        "player_id": "fl-theo-hernandez",
        "name": "Theo Hernández",
        "nation": "🇫🇷",
        "club": "AC Milan",
        "position": "DEF",
        "secondary_positions": ["LB", "LWB"],
        "rarity": "EPIC",
        "ovr": 89,
        "pace": 95,
        "shooting": 73,
        "passing": 79,
        "dribbling": 86,
        "defending": 78,
        "physical": 90,
        "preferred_foot": "Left",
        "traits": ["Overlapping Fullback", "Power Runner"],
    },
    {
        "player_id": "fl-achraf-hakimi",
        "name": "Achraf Hakimi",
        "nation": "🇲🇦",
        "club": "Paris Saint-Germain",
        "position": "DEF",
        "secondary_positions": ["RB", "RWB"],
        "rarity": "EPIC",
        "ovr": 88,
        "pace": 96,
        "shooting": 74,
        "passing": 83,
        "dribbling": 87,
        "defending": 76,
        "physical": 78,
        "preferred_foot": "Right",
        "traits": ["Rapid", "Cross Specialist"],
    },
    {
        "player_id": "fl-rodri",
        "name": "Rodri",
        "nation": "🇪🇸",
        "club": "Manchester City",
        "position": "MID",
        "secondary_positions": ["CDM"],
        "rarity": "LEGENDARY",
        "ovr": 97,
        "pace": 72,
        "shooting": 73,
        "passing": 94,
        "dribbling": 82,
        "defending": 89,
        "physical": 91,
        "preferred_foot": "Right",
        "traits": ["Deep-Lying Playmaker", "Press Resistant"],
    },
    {
        "player_id": "fl-pedri",
        "name": "Pedri",
        "nation": "🇪🇸",
        "club": "Barcelona",
        "position": "MID",
        "secondary_positions": ["CM", "CAM"],
        "rarity": "EPIC",
        "ovr": 91,
        "pace": 80,
        "shooting": 62,
        "passing": 92,
        "dribbling": 94,
        "defending": 55,
        "physical": 61,
        "preferred_foot": "Right",
        "traits": ["Technical", "Playmaker"],
    },
    {
        "player_id": "fl-bruno-fernandes",
        "name": "Bruno Fernandes",
        "nation": "🇵🇹",
        "club": "Manchester United",
        "position": "MID",
        "secondary_positions": ["CAM"],
        "rarity": "ELITE",
        "ovr": 88,
        "pace": 73,
        "shooting": 86,
        "passing": 91,
        "dribbling": 85,
        "defending": 57,
        "physical": 70,
        "preferred_foot": "Right",
        "traits": ["Dead Ball", "Chance Creator"],
    },
    {
        "player_id": "fl-vinicius-jr",
        "name": "Vinícius Jr.",
        "nation": "🇧🇷",
        "club": "Real Madrid",
        "position": "ATT",
        "secondary_positions": ["LW"],
        "rarity": "LEGENDARY",
        "ovr": 95,
        "pace": 97,
        "shooting": 88,
        "passing": 83,
        "dribbling": 98,
        "defending": 35,
        "physical": 75,
        "preferred_foot": "Right",
        "traits": ["Creative Dribbler", "Finesse Shot"],
    },
    {
        "player_id": "fl-harry-kane",
        "name": "Harry Kane",
        "nation": "🏴",
        "club": "Bayern Munich",
        "position": "ATT",
        "secondary_positions": ["ST"],
        "rarity": "ELITE",
        "ovr": 93,
        "pace": 68,
        "shooting": 95,
        "passing": 88,
        "dribbling": 83,
        "defending": 44,
        "physical": 89,
        "preferred_foot": "Right",
        "traits": ["Target Man", "Power Shot"],
    },
    {
        "player_id": "fl-bukayo-saka",
        "name": "Bukayo Saka",
        "nation": "🏴",
        "club": "Arsenal",
        "position": "ATT",
        "secondary_positions": ["RW"],
        "rarity": "EPIC",
        "ovr": 89,
        "pace": 88,
        "shooting": 82,
        "passing": 84,
        "dribbling": 91,
        "defending": 52,
        "physical": 70,
        "preferred_foot": "Left",
        "traits": ["Technical", "Cross Specialist"],
    },
    {
        "player_id": "fl-lionel-messi",
        "name": "Lionel Messi",
        "nation": "🇦🇷",
        "club": "Inter Miami",
        "position": "ATT",
        "secondary_positions": ["RW", "CAM"],
        "rarity": "ICONIC",
        "ovr": 97,
        "pace": 91,
        "shooting": 96,
        "passing": 97,
        "dribbling": 99,
        "defending": 38,
        "physical": 70,
        "preferred_foot": "Left",
        "traits": ["Playmaker", "Technical", "Dead Ball", "Finesse Shot"],
    },
    {
        "player_id": "fl-erling-haaland",
        "name": "Erling Haaland",
        "nation": "🇳🇴",
        "club": "Manchester City",
        "position": "ATT",
        "secondary_positions": ["ST"],
        "rarity": "LEGENDARY",
        "ovr": 96,
        "pace": 89,
        "shooting": 99,
        "passing": 72,
        "dribbling": 80,
        "defending": 45,
        "physical": 97,
        "preferred_foot": "Left",
        "traits": ["Poacher", "Aerial Threat", "Power Shot"],
    },
    {
        "player_id": "fl-kevin-de-bruyne",
        "name": "Kevin De Bruyne",
        "nation": "🇧🇪",
        "club": "Manchester City",
        "position": "MID",
        "secondary_positions": ["CM", "CAM"],
        "rarity": "LEGENDARY",
        "ovr": 94,
        "pace": 74,
        "shooting": 88,
        "passing": 98,
        "dribbling": 87,
        "defending": 53,
        "physical": 78,
        "preferred_foot": "Right",
        "traits": ["Long Ball", "Chance Creator", "Dead Ball"],
    },
    {
        "player_id": "fl-alisson",
        "name": "Alisson Becker",
        "nation": "🇧🇷",
        "club": "Liverpool",
        "position": "GK",
        "secondary_positions": [],
        "rarity": "ELITE",
        "ovr": 89,
        "pace": 45,
        "shooting": 30,
        "passing": 85,
        "dribbling": 45,
        "defending": 91,
        "physical": 86,
        "preferred_foot": "Right",
        "traits": ["Sweeper Keeper", "Long Throw"],
    },
    {
        "player_id": "fl-virgil-van-dijk",
        "name": "Virgil van Dijk",
        "nation": "🇳🇱",
        "club": "Liverpool",
        "position": "DEF",
        "secondary_positions": ["CB"],
        "rarity": "LEGENDARY",
        "ovr": 91,
        "pace": 78,
        "shooting": 33,
        "passing": 86,
        "dribbling": 50,
        "defending": 95,
        "physical": 93,
        "preferred_foot": "Right",
        "traits": ["Aerial Threat", "Leader"],
    },
    {
        "player_id": "fl-mohamed-salah",
        "name": "Mohamed Salah",
        "nation": "🇪🇬",
        "club": "Liverpool",
        "position": "ATT",
        "secondary_positions": ["RW"],
        "rarity": "LEGENDARY",
        "ovr": 93,
        "pace": 93,
        "shooting": 91,
        "passing": 84,
        "dribbling": 94,
        "defending": 45,
        "physical": 76,
        "preferred_foot": "Left",
        "traits": ["Finesse Shot", "Inside Forward"],
    },
]

COMPETITIONS = {
    "playcl": ("🏆", "Champions League", "UCL"),
    "playwc": ("🌍", "World Cup", "WC"),
    "playacl": ("🌏", "Asian Champions League", "ACL"),
}

COMPETITION_TEAMS = {
    "playcl": {
        "madrid": ("🇪🇸", "Real Madrid", 92),
        "barcelona": ("🔵🔴", "Barcelona", 89),
        "man-city": ("🔷", "Manchester City", 91),
        "bayern": ("🔴", "Bayern Munich", 90),
        "liverpool": ("🔴", "Liverpool", 89),
        "arsenal": ("🔴", "Arsenal", 86),
        "psg": ("🔵", "Paris Saint-Germain", 87),
        "inter": ("🔵⚫", "Inter Milan", 86),
    },
    "playwc": {
        "argentina": ("🇦🇷", "Argentina", 91),
        "portugal": ("🇵🇹", "Portugal", 88),
        "brazil": ("🇧🇷", "Brazil", 89),
        "france": ("🇫🇷", "France", 90),
        "spain": ("🇪🇸", "Spain", 88),
        "germany": ("🇩🇪", "Germany", 86),
        "england": ("🏴", "England", 89),
        "india": ("🇮🇳", "India", 73),
    },
    "playacl": {
        "al-hilal": ("🔵", "Al Hilal", 83),
        "al-nassr": ("🟡", "Al Nassr", 80),
        "al-ain": ("🟣", "Al Ain", 76),
        "urawa": ("🔴", "Urawa Red Diamonds", 78),
        "jeonbuk": ("🟢", "Jeonbuk Hyundai Motors", 77),
        "yokohama": ("🔵", "Yokohama F. Marinos", 76),
        "buriram": ("🔵", "Buriram United", 74),
        "gwangju": ("🟠", "Gwangju FC", 73),
    },
}

# A small, named launch catalogue for the three built-in game modes. These
# players are competition opponents only; MongoDatabase marks them as
# non-claimable when it materializes the catalogue.
MODE_ROSTERS = {
    "playcl": {
        "madrid": [
            ("Thibaut Courtois", "GK"), ("Dani Carvajal", "DEF"), ("Antonio Rüdiger", "DEF"),
            ("David Alaba", "DEF"), ("Jude Bellingham", "MID"), ("Federico Valverde", "MID"),
            ("Luka Modrić", "MID"), ("Vinícius Jr.", "ATT"), ("Kylian Mbappé", "ATT"),
            ("Rodrygo", "ATT"), ("Brahim Díaz", "ATT"),
        ],
        "barcelona": [
            ("Marc-André ter Stegen", "GK"), ("Jules Koundé", "DEF"), ("Ronald Araújo", "DEF"),
            ("Alejandro Balde", "DEF"), ("Pedri", "MID"), ("Frenkie de Jong", "MID"),
            ("Gavi", "MID"), ("Lamine Yamal", "ATT"), ("Robert Lewandowski", "ATT"),
            ("Raphinha", "ATT"), ("Ferran Torres", "ATT"),
        ],
        "man-city": [
            ("Ederson", "GK"), ("Kyle Walker", "DEF"), ("Rúben Dias", "DEF"),
            ("Joško Gvardiol", "DEF"), ("Rodri", "MID"), ("Kevin De Bruyne", "MID"),
            ("Phil Foden", "MID"), ("Erling Haaland", "ATT"), ("Jérémy Doku", "ATT"),
            ("Savinho", "ATT"), ("Jack Grealish", "ATT"),
        ],
        "bayern": [
            ("Manuel Neuer", "GK"), ("Joshua Kimmich", "DEF"), ("Dayot Upamecano", "DEF"),
            ("Alphonso Davies", "DEF"), ("Jamal Musiala", "MID"), ("Leon Goretzka", "MID"),
            ("Michael Olise", "MID"), ("Harry Kane", "ATT"), ("Leroy Sané", "ATT"),
            ("Serge Gnabry", "ATT"), ("Kingsley Coman", "ATT"),
        ],
        "liverpool": [
            ("Alisson Becker", "GK"), ("Trent Alexander-Arnold", "DEF"), ("Ibrahima Konaté", "DEF"),
            ("Virgil van Dijk", "DEF"), ("Alexis Mac Allister", "MID"), ("Dominik Szoboszlai", "MID"),
            ("Ryan Gravenberch", "MID"), ("Mohamed Salah", "ATT"), ("Darwin Núñez", "ATT"),
            ("Luis Díaz", "ATT"), ("Cody Gakpo", "ATT"),
        ],
    },
    "playwc": {
        "argentina": [
            ("Emiliano Martínez", "GK"), ("Nahuel Molina", "DEF"), ("Cristian Romero", "DEF"),
            ("Nicolás Otamendi", "DEF"), ("Rodrigo De Paul", "MID"), ("Enzo Fernández", "MID"),
            ("Alexis Mac Allister", "MID"), ("Lionel Messi", "ATT"), ("Julián Álvarez", "ATT"),
            ("Lautaro Martínez", "ATT"), ("Ángel Di María", "ATT"),
        ],
        "portugal": [
            ("Diogo Costa", "GK"), ("João Cancelo", "DEF"), ("Rúben Dias", "DEF"),
            ("Pepe", "DEF"), ("Bruno Fernandes", "MID"), ("Bernardo Silva", "MID"),
            ("Vitinha", "MID"), ("Cristiano Ronaldo", "ATT"), ("Rafael Leão", "ATT"),
            ("Diogo Jota", "ATT"), ("João Félix", "ATT"),
        ],
        "brazil": [
            ("Alisson Becker", "GK"), ("Danilo", "DEF"), ("Marquinhos", "DEF"),
            ("Éder Militão", "DEF"), ("Casemiro", "MID"), ("Bruno Guimarães", "MID"),
            ("Lucas Paquetá", "MID"), ("Neymar", "ATT"), ("Vinícius Jr.", "ATT"),
            ("Rodrygo", "ATT"), ("Richarlison", "ATT"),
        ],
        "france": [
            ("Mike Maignan", "GK"), ("Jules Koundé", "DEF"), ("William Saliba", "DEF"),
            ("Dayot Upamecano", "DEF"), ("Aurélien Tchouaméni", "MID"), ("Eduardo Camavinga", "MID"),
            ("Antoine Griezmann", "MID"), ("Kylian Mbappé", "ATT"), ("Ousmane Dembélé", "ATT"),
            ("Olivier Giroud", "ATT"), ("Kingsley Coman", "ATT"),
        ],
        "spain": [
            ("Unai Simón", "GK"), ("Dani Carvajal", "DEF"), ("Aymeric Laporte", "DEF"),
            ("Robin Le Normand", "DEF"), ("Rodri", "MID"), ("Pedri", "MID"),
            ("Dani Olmo", "MID"), ("Lamine Yamal", "ATT"), ("Álvaro Morata", "ATT"),
            ("Nico Williams", "ATT"), ("Ferran Torres", "ATT"),
        ],
    },
    "playacl": {
        "al-hilal": [
            ("Yassine Bounou", "GK"), ("João Cancelo", "DEF"), ("Kalidou Koulibaly", "DEF"),
            ("Renan Lodi", "DEF"), ("Rúben Neves", "MID"), ("Sergej Milinković-Savić", "MID"),
            ("Malcom", "MID"), ("Salem Al-Dawsari", "ATT"), ("Aleksandar Mitrović", "ATT"),
            ("Marcos Leonardo", "ATT"), ("Michael", "ATT"),
        ],
        "al-nassr": [
            ("Bento", "GK"), ("Sultan Al-Ghannam", "DEF"), ("Aymeric Laporte", "DEF"),
            ("Ali Lajami", "DEF"), ("Marcelo Brozović", "MID"), ("Otávio", "MID"),
            ("Sadio Mané", "MID"), ("Cristiano Ronaldo", "ATT"), ("Jhon Durán", "ATT"),
            ("Anderson Talisca", "ATT"), ("Wesley", "ATT"),
        ],
        "al-ain": [
            ("Patricio", "GK"), ("Erik", "DEF"), ("Kouadio-Yves Dabila", "DEF"),
            ("Park Yong-woo", "DEF"), ("Mohammed Abbas", "MID"), ("Yahia Nader", "MID"),
            ("Kaku", "MID"), ("Soufiane Rahimi", "ATT"), ("Kodjo Laba", "ATT"),
            ("Matías Palacios", "ATT"), ("Laba Kordje", "ATT"),
        ],
        "urawa": [
            ("Shusaku Nishikawa", "GK"), ("Hirokazu Ishihara", "DEF"), ("Alexander Scholz", "DEF"),
            ("Marius Hoibraten", "DEF"), ("Samuel Gustafson", "MID"), ("Kaito Yasui", "MID"),
            ("Takahiro Sekine", "MID"), ("Thiago Santana", "ATT"), ("Yusuke Matsuo", "ATT"),
            ("Ryoma Watanabe", "ATT"), ("Toshiki Takahashi", "ATT"),
        ],
        "jeonbuk": [
            ("Kim Jung-hoon", "GK"), ("Choi Chul-soon", "DEF"), ("Park Jin-seop", "DEF"),
            ("Hong Jeong-ho", "DEF"), ("Park Yong-woo", "MID"), ("Lee Seung-woo", "MID"),
            ("Han Kyo-won", "MID"), ("Song Min-kyu", "ATT"), ("Moon Seon-min", "ATT"),
            ("Tiago Orobó", "ATT"), ("André Luís", "ATT"),
        ],
    },
}
